# These are supported funding model platforms

github: kernelshard
# patreon: your-patreon-username
# open_collective: your-open-collective
# ko_fi: your-ko-fi-username
# tidelift: npm/otelkit
# community_bridge: your-project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# polar: your-polar-username
# buy_me_a_coffee: your-buy-me-a-coffee-username
# custom: ['https://your-custom-url.com']
