site_name: otelkit
site_description: HTTP middleware for automatic request tracing with OpenTelemetry
site_author: kernelshard
site_url: https://kernelshard.github.io/otelkit/

repo_name: kernelshard/otelkit
repo_url: https://github.com/kernelshard/otelkit

docs_dir: docs
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started: GETTING_STARTED.md
  - API Reference: API_REFERENCE.md
  - Advanced Usage: ADVANCED_USAGE.md
  - Integration Guides: INTEGRATION_GUIDES.md
  - Integration Testing: INTEGRATION_TESTING.md
  - Migration Guide: MIGRATION_GUIDE.md
  - Troubleshooting: TROUBLESHOOTING.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kernelshard/otelkit

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true